table daily_mature_metrics

	measure 'Daily gross conversion' = AVERAGE(daily_mature_metrics[gross_conversion])
		formatString: 0.00%

	measure 'Daily net conversion' = AVERAGE(daily_mature_metrics[net_conversion])
		formatString: 0.00%

	column event_date
		dataType: dateTime
		summarizeBy: none
		sourceColumn: event_date

	column experiment_group
		dataType: string
		summarizeBy: none
		sourceColumn: experiment_group

	column pageviews
		dataType: int64
		summarizeBy: none
		sourceColumn: pageviews

	column clicks
		dataType: int64
		summarizeBy: none
		sourceColumn: clicks

	column enrollments
		dataType: int64
		summarizeBy: none
		sourceColumn: enrollments

	column payments
		dataType: int64
		summarizeBy: none
		sourceColumn: payments

	column click_through_rate
		dataType: double
		formatString: 0.00%
		summarizeBy: none
		sourceColumn: click_through_rate

	column gross_conversion
		dataType: double
		formatString: 0.00%
		summarizeBy: none
		sourceColumn: gross_conversion

	column net_conversion
		dataType: double
		formatString: 0.00%
		summarizeBy: none
		sourceColumn: net_conversion

	column retention
		dataType: double
		formatString: 0.00%
		summarizeBy: none
		sourceColumn: retention

	partition daily_mature_metrics = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(#"DataFolder" & "\daily_mature_metrics.csv"), [Delimiter=",", Columns=10, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Headers, {{"event_date", type date}, {"experiment_group", type text}, {"pageviews", Int64.Type}, {"clicks", Int64.Type}, {"enrollments", Int64.Type}, {"payments", Int64.Type}, {"click_through_rate", type number}, {"gross_conversion", type number}, {"net_conversion", type number}, {"retention", type number}}, "en-US")
			in
				Typed
