table funnel

	column experiment_group
		dataType: string
		summarizeBy: none
		sourceColumn: experiment_group

	column stage_order
		dataType: int64
		summarizeBy: none
		sourceColumn: stage_order

	column stage
		dataType: string
		summarizeBy: none
		sourceColumn: stage

	column users
		dataType: int64
		summarizeBy: none
		sourceColumn: users

	partition funnel = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(#"DataFolder" & "\funnel.csv"), [Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Headers, {{"experiment_group", type text}, {"stage_order", Int64.Type}, {"stage", type text}, {"users", Int64.Type}}, "en-US")
			in
				Typed
