table group_summary

	measure 'Control gross conversion' = CALCULATE(MAX(group_summary[gross_conversion]), group_summary[experiment_group] = "Control")
		formatString: 0.00%

	measure 'Experiment gross conversion' = CALCULATE(MAX(group_summary[gross_conversion]), group_summary[experiment_group] = "Experiment")
		formatString: 0.00%

	measure 'Control net conversion' = CALCULATE(MAX(group_summary[net_conversion]), group_summary[experiment_group] = "Control")
		formatString: 0.00%

	measure 'Experiment net conversion' = CALCULATE(MAX(group_summary[net_conversion]), group_summary[experiment_group] = "Experiment")
		formatString: 0.00%

	column experiment_group
		dataType: string
		summarizeBy: none
		sourceColumn: experiment_group

	column pageviews
		dataType: int64
		summarizeBy: none
		sourceColumn: pageviews

	column clicks
		dataType: int64
		summarizeBy: none
		sourceColumn: clicks

	column mature_pageviews
		dataType: int64
		summarizeBy: none
		sourceColumn: mature_pageviews

	column mature_clicks
		dataType: int64
		summarizeBy: none
		sourceColumn: mature_clicks

	column enrollments
		dataType: int64
		summarizeBy: none
		sourceColumn: enrollments

	column payments
		dataType: int64
		summarizeBy: none
		sourceColumn: payments

	column click_through_rate
		dataType: double
		formatString: 0.00%
		summarizeBy: none
		sourceColumn: click_through_rate

	column gross_conversion
		dataType: double
		formatString: 0.00%
		summarizeBy: none
		sourceColumn: gross_conversion

	column net_conversion
		dataType: double
		formatString: 0.00%
		summarizeBy: none
		sourceColumn: net_conversion

	column retention
		dataType: double
		formatString: 0.00%
		summarizeBy: none
		sourceColumn: retention

	partition group_summary = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(#"DataFolder" & "\group_summary.csv"), [Delimiter=",", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Headers, {{"experiment_group", type text}, {"pageviews", Int64.Type}, {"clicks", Int64.Type}, {"mature_pageviews", Int64.Type}, {"mature_clicks", Int64.Type}, {"enrollments", Int64.Type}, {"payments", Int64.Type}, {"click_through_rate", type number}, {"gross_conversion", type number}, {"net_conversion", type number}, {"retention", type number}}, "en-US")
			in
				Typed
